name: speech_tools
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - geopandas==1.0.1
  - matplotlib==3.9.2
  - numpy==2.0.0
  - pandas==2.2.2
  - seaborn==0.13.2
  - pip:
      - pySankey
      - textwrap